export const art_collections = [
    {
      rank: 1,
      imageUrl: 'https://picsum.photos/seed/1/40',
      name: 'Celestial Realms',
      alt: 'Celestial Realms Collection',
      floorPrice: '$5',
      volume: '52k',
    },
    {
      rank: 2,
      imageUrl: 'https://picsum.photos/seed/2/40',
      name: 'Pixelated Portraits',
      alt: 'Pixelated Portraits Collection',
      floorPrice: '$8',
      volume: '96k',
    },
    {
      rank: 3,
      imageUrl: 'https://picsum.photos/seed/3/40',
      name: 'Aether Artifacts',
      alt: 'Aether Artifacts Collection',
      floorPrice: '$10',
      volume: '75k',
    },
    {
      rank: 4,
      imageUrl: 'https://picsum.photos/seed/4/40',
      name: 'Whimsical Wonders',
      alt: 'Whimsical Wonders Collection',
      floorPrice: '$12',
      volume: '88k',
    },
    {
      rank: 5,
      imageUrl: 'https://picsum.photos/seed/5/40',
      name: 'Mystic Motifs',
      alt: 'Mystic Motifs Collection',
      floorPrice: '$9',
      volume: '104k',
    },
    {
      rank: 6,
      imageUrl: 'https://picsum.photos/seed/6/40',
      name: 'Ephemeral Echos',
      alt: 'Ephemeral Echos Collection',
      floorPrice: '$7',
      volume: '63k',
    },
  ];