export const music_collections = [
    {
      rank: 1,
      imageUrl: 'https://picsum.photos/seed/7/40',
      name: 'Sonic Chronicles',
      alt: 'Sonic Chronicles Collection',
      floorPrice: '$10',
      volume: '105k',
    },
    {
      rank: 2,
      imageUrl: 'https://picsum.photos/seed/8/40',
      name: 'Euphonic Waves',
      alt: 'Euphonic Waves Collection',
      floorPrice: '$9',
      volume: '92k',
    },
    {
      rank: 3,
      imageUrl: 'https://picsum.photos/seed/9/40',
      name: 'Rhythmic Resonance',
      alt: 'Rhythmic Resonance Collection',
      floorPrice: '$7',
      volume: '81k',
    },
    {
      rank: 4,
      imageUrl: 'https://picsum.photos/seed/10/40',
      name: 'Melodic Memories',
      alt: 'Melodic Memories Collection',
      floorPrice: '$12',
      volume: '108k',
    },
    {
      rank: 5,
      imageUrl: 'https://picsum.photos/seed/11/40',
      name: 'Harmonic Hues',
      alt: 'Harmonic Hues Collection',
      floorPrice: '$11',
      volume: '98k',
    },
    {
      rank: 6,
      imageUrl: 'https://picsum.photos/seed/12/40',
      name: 'Tuned Tales',
      alt: 'Tuned Tales Collection',
      floorPrice: '$8',
      volume: '69k',
    },
  ];