export const sports_collections = [
    {
      rank: 1,
      imageUrl: 'https://picsum.photos/seed/13/40',
      name: 'Arena Anthems',
      alt: 'Arena Anthems Collection',
      floorPrice: '$12',
      volume: '110k',
    },
    {
      rank: 2,
      imageUrl: 'https://picsum.photos/seed/14/40',
      name: 'Stadium Stalwarts',
      alt: 'Stadium Stalwarts Collection',
      floorPrice: '$9',
      volume: '95k',
    },
    {
      rank: 3,
      imageUrl: 'https://picsum.photos/seed/15/40',
      name: 'Pitch Pioneers',
      alt: 'Pitch Pioneers Collection',
      floorPrice: '$11',
      volume: '85k',
    },
    {
      rank: 4,
      imageUrl: 'https://picsum.photos/seed/16/40',
      name: 'Court Champions',
      alt: 'Court Champions Collection',
      floorPrice: '$14',
      volume: '102k',
    },
    {
      rank: 5,
      imageUrl: 'https://picsum.photos/seed/17/40',
      name: 'Track Titans',
      alt: 'Track Titans Collection',
      floorPrice: '$13',
      volume: '89k',
    },
    {
      rank: 6,
      imageUrl: 'https://picsum.photos/seed/18/40',
      name: 'Field Frontiers',
      alt: 'Field Frontiers Collection',
      floorPrice: '$10',
      volume: '91k',
    },
  ];