export const top_collections = [
    {
      rank: 1,
      imageUrl: 'https://picsum.photos/seed/19/40',
      name: 'Celestial Ciphers',
      alt: 'Celestial Ciphers Collection',
      floorPrice: '$14',
      volume: '117k',
    },
    {
      rank: 2,
      imageUrl: 'https://picsum.photos/seed/20/40',
      name: 'Quantum Quirks',
      alt: 'Quantum Quirks Collection',
      floorPrice: '$15',
      volume: '120k',
    },
    {
      rank: 3,
      imageUrl: 'https://picsum.photos/seed/21/40',
      name: 'Nexus Novelties',
      alt: 'Nexus Novelties Collection',
      floorPrice: '$13',
      volume: '108k',
    },
    {
      rank: 4,
      imageUrl: 'https://picsum.photos/seed/22/40',
      name: 'Stellar Signatures',
      alt: 'Stellar Signatures Collection',
      floorPrice: '$16',
      volume: '112k',
    },
    {
      rank: 5,
      imageUrl: 'https://picsum.photos/seed/23/40',
      name: 'Dimensional Drifts',
      alt: 'Dimensional Drifts Collection',
      floorPrice: '$12',
      volume: '100k',
    },
    {
      rank: 6,
      imageUrl: 'https://picsum.photos/seed/24/40',
      name: 'Cosmic Curiosities',
      alt: 'Cosmic Curiosities Collection',
      floorPrice: '$11',
      volume: '104k',
    },
  ];